site:
  posts_per_run: 2
  category_names: ["レビュー", "比較", "おすすめ"]
  affiliate_disclosure: "当サイトはアフィリエイト広告（Amazonアソシエイト含む）を利用しています。"
  unique_slug_date: true
  internal_link: ""   # 内部リンク先があればURLを入れる

llm:
  model: gpt-5
  fallback_models:
    - gpt-4o
    - gpt-4o-mini
  temperature: 0.4

data_sources:
  rakuten:
    endpoint: https://app.rakuten.co.jp/services/api/IchibaItem/Search/20220601
    max_per_seed: 60     # 30件×最大2ページ=60
    genreId: null        # 必要なら数値IDを設定

content:
  price_floor: 2000      # 価格の下限（円）
  review_floor: 3.8      # レビュー平均の下限
  min_items: 3           # 比較に最低必要な件数
  ab_test: false

review:
  rules_file: src/review_rules.yaml

keywords:
  mode: expand_llm        # LLMでロングテールを拡張
  max_candidates: 40
  seeds:                  # 起点にしたいキーワード（任意・空でも可）
    - "USB充電器 65W"
    - "電動歯ブラシ コスパ"
  pools:                  # 多ジャンルを広げる素片
    nouns:
      - "モバイルバッテリー"
      - "USB充電器"
      - "加湿器"
      - "空気清浄機"
      - "ロボット掃除機"
      - "ドライブレコーダー"
      - "ゲーミングキーボード"
      - "モニターライト"
      - "ベビーモニター"
      - "ヘアドライヤー"
      - "オーブントースター"
      - "コーヒーメーカー"
      - "ポータブル電源"
      - "LEDデスクライト"
      - "ハンディクリーナー"
    modifiers:
      - "コスパ"
      - "小型"
      - "静音"
      - "多機能"
      - "初心者向け"
      - "省エネ"
      - "軽量"
    specs:
      - "USB-C"
      - "65W"
      - "急速充電"
      - "Wi-Fi"
      - "Bluetooth"
      - "大容量"
  themes:
    - "家電"
    - "キッチン"
    - "日用品"
    - "ガジェット"
    - "カー用品"
    - "子育て"
    - "アウトドア"
    - "掃除"
    - "収納"
    - "照明"
    - "防犯"
    - "文房具"
