site:
  affiliate_disclosure: "当サイトはアフィリエイト広告（Amazonアソシエイト含む）を利用しています。"

llm:
  model: gpt-5
  fallback_models: ["gpt-4o", "gpt-4o-mini"]
  temperature: 0.35          # gpt-5には送られません（実装側で抑止）
  max_output_tokens: 6000
  timeout_sec: 120

keywords:
  # 幅広ジャンルにして当たりやすく
  seeds:
    - "USB充電器 65W"
    - "電動歯ブラシ コスパ"
    - "ロボット掃除機 静音"
    - "空気清浄機 小型"
    - "コーヒーメーカー 大容量"
    - "ヘアドライヤー 速乾"
    - "モニターライト 27インチ"
    - "加湿器 比較"
  per_run: 8                  # 1回あたりの試行数を増やす

rakuten:
  hits: 30                    # API上限に合わせる
  min_review_count: 5         # ← 10→5 に緩和
  min_price: 1000
  max_price: 9999999
  min_items_after_filters: 2   # ← 3→2 に緩和（薄い市場でも拾える）

content:
  min_chars: 1800             # ← 2000→1800（落ちにくく）
  require_tables: 1
  require_buttons: 3

wp:
  category_ids: []
  tag_ids: []

debug:
  draft_mode: false
