site:
  posts_per_run: 2
  category_names: ["レビュー", "おすすめ"]
  affiliate_disclosure: "当サイトはアフィリエイト広告（Amazonアソシエイト含む）を利用しています。"
  unique_slug_date: true
  internal_link: ""

keywords:
  mode: pools
  max_candidates: 20
  seeds:
    - "USB-C ドッキングステーション"
  pools:
    nouns:
      - "ヘアドライヤー"
      - "布団乾燥機"
      - "加湿器"
      - "空気清浄機"
      - "電動歯ブラシ"
      - "オーブントースター"
      - "炊飯器"
      - "コーヒーメーカー"
      - "ホットサンドメーカー"
      - "電気ケトル"
      - "ゲーミングマウス"
      - "ゲーミングキーボード"
      - "モニターライト"
      - "外付けSSD"
      - "モバイルバッテリー"
      - "USB充電器"
      - "ロボット掃除機"
      - "ポータブル電源"
      - "ドライブレコーダー"
      - "ベビーモニター"
    modifiers:
      - "おすすめ"
      - "比較"
      - "コスパ"
      - "静音"
      - "小型"
      - "一人暮らし"
      - "初心者向け"
      - "日本メーカー"
      - "大容量"
    specs:
      - "急速充電"
      - "省エネ"
      - "軽量"
      - "多機能"
      - "Wi-Fi対応"
  themes:
    - "家電"
    - "キッチン"
    - "日用品"
    - "ガジェット"
    - "カー用品"
    - "子育て"
    - "アウトドア"
    - "掃除"
    - "収納"
    - "照明"
    - "文房具"
    - "防犯"

data_sources:
  rakuten:
    endpoint: "https://app.rakuten.co.jp/services/api/IchibaItem/Search/20220601"
    max_per_seed: 90

content:
  min_items: 2
  price_floor: 500
  review_floor: 3.5
  ab_test: false

review:
  rules_file: "src/review_rules.yaml"

llm:
  model: "gpt5"                     # ← 希望モデル。未提供/未権限なら下記に自動フォールバック
  fallback_models:
    - "gpt-4o-mini"
    - "gpt-4o"
    - "o4-mini"
  temperature: 0.4
