site:
  affiliate_disclosure: "当サイトはアフィリエイト広告（Amazonアソシエイト含む）を利用しています。"

llm:
  provider: openai
  model: gpt-5
  fallback_models: ["gpt-4o", "gpt-4o-mini"]
  use_responses_api: true
  max_completion_tokens: 2800
  timeout_sec: 90
  retries: 1
  retry_backoff_sec: 2
  soft_timeout_fallback_sec: 45
  temperature: 0.3
  top_p: 0.9

keywords:
  seeds:
    - "USB充電器 65W"
    - "電動歯ブラシ コスパ"
    - "ロボット掃除機 静音"
    - "空気清浄機 小型"
    - "コーヒーメーカー 大容量"
    - "ヘアドライヤー 速乾"
    - "モニターライト 27インチ"
    - "加湿器 比較"
  per_run: 4

rakuten:
  hits: 30
  min_review_count: 5
  min_price: 1000
  max_price: 9999999
  min_items_after_filters: 2

content:
  min_chars: 1600         # 以前よりやや緩め
  require_tables: 0       # ← 一時的に緩和（table必須を外す）
  require_buttons: 0      # ← 一時的に緩和（CTA必須を外す）
  post_if_llm_ok: true    # LLM本文が得られれば投稿

wp:
  category_ids: []
  tag_ids: []

debug:
  draft_mode: false

alerts:
  include_events:
    - "POST_PUBLISHED"
    - "LLM_FAILED_FINAL"
    - "VALIDATION_FAILED"   # ← 一時的に可視化
