site:
  affiliate_disclosure: "当サイトはアフィリエイト広告（Amazonアソシエイト含む）を利用しています。"
  post_status: publish

llm:
  model: gpt-5            # 主モデル：Responses APIで叩く
  fallback_models:        # 自動フォールバック順
    - gpt-4o
    - gpt-4o-mini
  temperature: 0.35
  max_output_tokens: 6000   # chatのmax_tokensではなく「responses用」
  timeout_sec: 120

keywords:
  seeds:
    - "USB充電器 65W"
    - "電動歯ブラシ コスパ"
    - "空気清浄機 小型"
    - "ロボット掃除機 静音"
    - "コーヒーメーカー 大容量"
    - "ゲーミングキーボード 多機能"
  per_run: 6               # 1回のRunで試行する件数（拡張後の最終件数）

rakuten:
  hits: 30                 # API仕様の上限30
  min_review_count: 10
  min_items_after_filters: 3
  min_price: 0
  max_price: 9999999

content:
  min_chars: 2000          # 本文の最小文字数
  require_tables: 1        # 表の最低数（|の出現数で概判定）
  require_buttons: 3       # AFFINGERボタンの最低数

wp:
  category_ids: []         # 例: [3,7]
  tag_ids: []              # 例: [12,25]

debug:
  draft_mode: false        # trueにすると下書き投稿
