# draft-only preset（WP投稿しない）
mode: draft_only

site:
  brand: "simple-ni-yoku"
  affiliate_disclosure: "当サイトはアフィリエイト広告（Amazonアソシエイト含む）を利用しています。"
  timezone: "Asia/Tokyo"

keywords:
  per_run: 1   # 1本だけ安定生成
  seeds:
    - "USB充電器 65W"
    - "電動歯ブラシ コスパ"
    - "空気清浄機 小型"
    - "ロボット掃除機 静音"
    - "コーヒーメーカー 大容量"
    - "モニターライト 27インチ"
    - "ヘアドライヤー 日本メーカー"
    - "加湿器 比較"
    - "ポータブル電源 小型"
    - "ゲーミングキーボード 入門"

# LLM設定（gpt-5優先。失敗時は4o→4o-mini）
llm:
  model_primary: "gpt-5"
  fallback_models:
    - "gpt-4o"
    - "gpt-4o-mini"
  max_completion_tokens: 2200  # Responses APIの推奨キー名

# 記事の最低品質検証
validation:
  min_chars: 1500
  require_table: true
  require_cta_count: 3

# 比較軸のデフォルト（必要に応じて編集）
axes:
  - "耐久性"
  - "保証"
  - "カラーバリエーション"
  - "追加オプション"
  - "流通度合い"

# 楽天の候補ピック数（最終短縮）
shortlist_limit: 5
