name: publish
on:
  schedule:
    - cron: '30 21 * * *'   # 06:30 JST
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests pyyaml python-slugify openai

      - name: Run generator (hybrid: Rakuten + ChatGPT API)
        env:
          RAKUTEN_APP_ID: ${{ secrets.RAKUTEN_APP_ID }}
          WP_SITE_URL: ${{ secrets.WP_SITE_URL }}
          WP_USERNAME: ${{ secrets.WP_USERNAME }}
          WP_APP_PASSWORD: ${{ secrets.WP_APP_PASSWORD }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          ALERT_WEBHOOK_URL: ${{ secrets.ALERT_WEBHOOK_URL }}
        run: |
          python -u src/main.py --config config/app.yaml

      - name: Print run.log
        if: always()
        run: |
          if [ -f run.log ]; then
            echo '----- tail run.log -----'
            tail -n 400 run.log
          else
            echo 'run.log not found'
          fi

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: logs
          path: |
            run.log
            llm_prompt.json
            llm_output.txt
